task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 18 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /data1/extend_DEIM/addcharcntdataset/extra_morphr4cocotrain_addtitleteikokukoten/img
    ann_file: /data1/extend_DEIM/addcharcntdataset/extra_morphr4cocotrain_addtitleteikokukoten.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 3
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/t-aoike/smartocrproject/rtmdet/morphr4cocovalid/img
    ann_file: /home/t-aoike/smartocrproject/rtmdet/morphr4cocovalid/morphr4cocovalid_addtitle.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 3
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction